### ISSUE TITLE
Laporan KIB Kode 108

### ISSUE THREAD

**Issue by fauazan-muntaza** [muntaza/catatan_openaset_balangan#3]
Buat untuk Modul Kabupaten, KIB A-F dengan kode Barang 108

@muntaza 

setelah fitur #1 tentunya

- [ ] perbaikan ER

**Comment by muntaza** [comment]
On Progres. SQL KIB A, B, C sudah OK. Perbaikan script. semua file di susun
[https://github.com/muntaza/catatan_openaset_balangan/commit/206176a110f8b9c19d7f598d5c6595540c5ef191](url)

**Comment by muntaza** [comment]
Di harapkan Khusus KIB dulu

**Comment by muntaza** [comment]
Sudah di Aplikasikan

[commit](https://github.com/muntaza/catatan_openaset_balangan/commit/0d3811bf01a81dbaffe8bfae9cb67e61c892ea84)
